apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-task-platform
resources:
  - ../../base
patchesStrategicMerge:
  - patch-replicas.yaml
images:
  - name: YOUR_DOCKERHUB_USERNAME/ai-task-backend
    newTag: v1.0.0
  - name: YOUR_DOCKERHUB_USERNAME/ai-task-worker
    newTag: v1.0.0
  - name: YOUR_DOCKERHUB_USERNAME/ai-task-frontend
    newTag: v1.0.0
